Fixes #54 added code of conduct and linked it in readme.md
Kota-Karthik/twinTrim pull request #68
Opened 2024-10-04 16:59 UTC by ShirshenduR

## Description

This change introduces a **Code of Conduct** to the TwinTrim project, ensuring that all participants in the project adhere to a set of community guidelines promoting respect, inclusivity, and professionalism. It connects the `CODE_OF_CONDUCT.md` file with the project’s `README.md`, informing contributors about its existence and importance.

- Fixes #54 @Kota-Karthik 

## Type of change

- [x] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have maintained a clean commit history by using the necessary Git commands
- [x] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

N/A (Not necessary for this documentation change)

2024-10-04 19:56 UTC, techy4shri commented
Rejected due to violations of rules of the program. This is a warning, kindly do not copy paste or else you might get banned from the program.

2024-10-04 20:06 UTC, techy4shri reviewed
This code of conduct is customized for a large project, kindly make changes to suit this current repository.

2024-10-04 20:06 UTC, techy4shri commented on CODE_OF_CONDUCT.md
> +## Our Pledge
This plege is for a community project repository, not for an individual owned one. Rewrite it or remove it.

2024-10-04 20:06 UTC, techy4shri commented on CODE_OF_CONDUCT.md
> +We, as members and maintainers of the **TwinTrim** project, pledge to foster a welcoming, inclusive, and harassment-free environment for everyone involved. Whether you are contributing code, writing
Again, there is only one maintainer here, and this is extremely lengthy and unnecessary.

2024-10-04 20:07 UTC, techy4shri requested changes
Unless the changes are made, this cannot be merged.

2024-10-04 20:10 UTC, techy4shri requested changes
Mkae the necessary changes.

2024-10-04 20:10 UTC, techy4shri commented on CODE_OF_CONDUCT.md
> +We, as members and maintainers of the **TwinTrim** project, pledge to foster a welcoming, inclusive, and harassment-free environment for everyone involved. Whether you are contributing code, writing
This is for a community, a large one. The repository is individually owned and you need to keep that in mind.

2024-10-04 20:10 UTC, techy4shri commented on CODE_OF_CONDUCT.md
> +3. **Confidentiality**: The project team is committed to protecting the privacy and confidentiality of all parties involved in a complaint, including the reporter.
this is not a step, either remove it or put the first two in indentation.

2024-10-06 12:15 UTC, ShirshenduR commented
@Kota-Karthik Please check

2024-10-06 13:39 UTC, techy4shri approved these changes
Looks good to me.

2024-10-06 13:40 UTC, merged