Add --dry-run Functionality to TwinTrim for Safe Simulated Duplicate Removal
Kota-Karthik/twinTrim pull request #74
Opened 2024-10-05 12:46 UTC by adityakalburgi

This PR introduces a --dry-run option to TwinTrim, allowing users to simulate the duplicate removal process without making any changes. The feature is designed to give users a safe preview of what actions will be taken, ensuring they can confidently proceed with the actual duplicate removal process.

Key Changes:
Added the --dry-run flag to simulate file deletions.
Updated the core logic to handle the dry run mode.
Modified the README to include documentation

2024-10-05 13:40 UTC, Kota-Karthik commented
@adityakalburgi 
can you please add screenshots , for showing us how this new --dry-run mode looks

2024-10-06 13:27 UTC, adityakalburgi commented
ok will share it

2024-10-06 14:00 UTC, adityakalburgi commented
Hi! @Kota-Karthik  here is the screenshort how it works
1. when there were no duplicates in my directory
2. when i created duplicate in my directory
![Screenshot 2024-10-06 192359](https://github.com/user-attachments/assets/36f2b592-0db1-42c8-84a9-4958fb9e1e23)
![Screenshot 2024-10-06 192924](https://github.com/user-attachments/assets/424b9d04-be03-4471-975e-c9b312dfb8bb)

2024-10-06 14:17 UTC, techy4shri requested changes
Make these changes and wait for further review.

2024-10-06 14:17 UTC, techy4shri commented on README.md
> +- **Deadlock Prevention**: Implements locks to prevent deadlocks during multi-threaded operations, ensuring
recheck this line, remove the changes from here.

2024-10-06 14:17 UTC, techy4shri commented on README.md
> -    - Generates a unique hash for each file using MD5 to identify duplicates by content.
There is no change here, simply delete and paste.

2024-10-06 14:17 UTC, techy4shri commented on README.md
> +
again, same thing

2024-10-06 14:17 UTC, techy4shri commented on README.md
> +
add this under option where the optional commands are given.

2024-10-06 15:05 UTC, adityakalburgi reviewed
i have done the required changes

2024-10-06 17:01 UTC, techy4shri requested changes
I do not see the changes in option seciton in readme yet, kindly implement it.

2024-10-07 12:53 UTC, adityakalburgi commented
@techy4shri DONE!! I have added it in option section..

2024-10-07 13:18 UTC, techy4shri approved these changes
Approved! Everything is great! Thank you @adityakalburgi

2024-10-07 13:18 UTC, merged

2024-10-09 08:58 UTC, adityakalburgi commented
Hi! @Kota-Karthik can you please explain me what the issue is?..

2024-10-09 14:32 UTC, Kota-Karthik commented
@adityakalburgi go through the changes you made and try to run the project 
You will notice , you have many errors in updated code 
you can check your code