Optimize color palette in CLI
Kota-Karthik/twinTrim pull request #93
Opened 2024-10-07 16:22 UTC by mienpham04

## Description

Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.

- Fixes #24 

## Resolve inconsistent color palette in CLI

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] I have maintained a clean commit history by using the necessary Git commands
- [X] I have checked that my code does not cause any merge conflicts

## Screenshots (if applicable)

Add screenshots to help explain the changes (if necessary).
![image](https://github.com/user-attachments/assets/175c0d36-066c-475f-9981-5b3a260e0560)

2024-10-08 10:38 UTC, techy4shri requested changes
@mienpham04 do not remove anything unless required. I see that the logging is removed and so it the dry run function. 
Revert your changes, and only work on the solution you are assigned. 
Your task is to add distinct colours to different texts which appears in the CLI while the package runs, not remove features others added.
Define a colour pallete for each type, implement it, write a good description in your PR how and where the changes are implemented and then request review again.

2024-10-08 10:38 UTC, techy4shri commented on twinTrim/flags.py
> -@click.option("--dry-run", is_flag=True, help="Simulate the process without deleting files.")
Why did you remove this line? Do not remove anything without any reason, and if you do remove soemthing, always add a comment the reason.

2024-10-08 10:38 UTC, techy4shri commented on twinTrim/flags.py
> -import logging
why did you remove logging??

2024-10-08 10:40 UTC, techy4shri commented on twinTrim/utils.py
> +        click.echo(click.style(f"Deleted: {filepath}"))
do not change the utils file unless needed. Your task issue mentioned falgs.py only.

2024-10-08 15:00 UTC, Kota-Karthik commented
@mienpham04 You also have merge conflicts 
please fix them after making neccessary changes as per review

2024-10-15 15:55 UTC, techy4shri requested changes
I still see unresolved changes. I am closing this PR tomorrow if you do not respond.

2024-10-16 18:39 UTC, techy4shri commented
Closing this pull request due to unresponsiveness of the contributor.

2024-10-16 18:39 UTC, closed without merging